### ISSUE TITLE
Add support for topics endpoints

### ISSUE THREAD

**Issue by kytrinyx** [octokit/octokit.rb#933]
These are now available via the REST API.

- https://developer.github.com/v3/repos/#list-all-topics-for-a-repository
- https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository

**Comment by salaxander** [comment]
If there's opportunity to help out on this, I'd love to jump in. I've used this gem in the past, and I've been looking for a project to contribute to in my spare time :)

**Comment by tarebyte** [comment]
@salaxander feel free to take it on if you'd like!

**Comment by kytrinyx** [comment]
@salaxander that would be lovely 🌻

I don't think we have any documentation about adding support for new endpoints, but off the top of my head it's going to need:

* the implementation
* (probably) custom preview headers
* tests

There are other pull requests that have added support for endpoints which you can probably pattern your contribution off of.

**Comment by salaxander** [comment]
Awesome! I'll work on it over the next couple days :)

**Comment by salaxander** [comment]
@kytrinyx @tarebyte - Wondering if you two might be able to help kick me in the right direction on this :) I started on the all topics endpoint, and that seems to be working pretty well, however I'm getting a failure on the test I wrote.

Under /lib/octokit/client/repositories.rb I've got
```
def topics(repo, options = {})
        options[:accept] = "application/vnd.github.mercy-preview+json"
        paginate "#{Repository.path repo}/topics", options
      end
```
Then in the repositories_spec.rb
```
def topics(repo, options = {})
        options[:accept] = "application/vnd.github.mercy-preview+json"
        paginate "#{Repository.path repo}/topics", options
      end
```
Then when running the tests
```
Failures:

  1) Octokit::Client::Repositories.topics returns a repository's topics
     Failure/Error: topics = Octokit.topics("sferik/rails_admin")
     NoMethodError:
       undefined method `<<' for {:read_timeout=>60, :continue_timeout=>nil, :debug_output=>nil}:Hash
       Did you mean?  <
     # ./lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
     # ./lib/octokit/middleware/follow_redirects.rb:61:in `call'
     # ./lib/octokit/connection.rb:156:in `request'
     # ./lib/octokit/connection.rb:84:in `paginate'
     # ./lib/octokit/client/repositories.rb:494:in `topics'
     # ./lib/octokit.rb:46:in `method_missing'
     # ./spec/octokit/client/repositories_spec.rb:331:in `block (3 levels) in <top (required)>'
```

I tried following patterns for other endpoints, but I must be missing something (sorry, still familiarizing myself with the codebase!)

Any help you can provide is super appreciated!! :)
